behaviors:
  ButtonBone:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: demoButtonBone.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: demoButtonBone.demo
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 20000
    threaded: true
